name: Repeat.gg Tournament Automation

on:
  # Run automatically every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual runs for testing
  workflow_dispatch:

jobs:
  join-tournaments:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          echo "Chrome version: $CHROME_VERSION"
          
          # Get the latest ChromeDriver version for the installed Chrome
          CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_VERSION")
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
          
          # Download and install ChromeDriver
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip -q chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tournament automation
        env:
          # Recommended: Use complete auth data (export_auth_for_github.py)
          REPEAT_GG_AUTH_DATA: ${{ secrets.REPEAT_GG_AUTH_DATA }}
          # Fallback: Individual cookies (less reliable)
          REPEAT_GG_PHP_SESSION: ${{ secrets.REPEAT_GG_PHP_SESSION }}
          REPEAT_GG_HJ_SESSION: ${{ secrets.REPEAT_GG_HJ_SESSION }}
          REPEAT_GG_HJ_USER_SESSION: ${{ secrets.REPEAT_GG_HJ_USER_SESSION }}
          K_SERVICE: "github-actions"  # This triggers GitHub Actions mode in the script
          CHROMEDRIVER_PATH: "/usr/local/bin/chromedriver"
        run: |
          echo "Starting tournament automation..."
          python repeat-gg-automated.py
      
      - name: Upload logs (if needed)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs
          path: |
            *.log
          retention-days: 7
          if-no-files-found: ignore
